### ISSUE TITLE
Unknown burst type: 1101 rtl sdr

### ISSUE THREAD

**Issue by jurek4321** [szechyjs/dsd#77] opened 2018-01-31 08:32 UTC
When i decoding using dsd on linux i always get error Unknown burst type: 1101

`uname -a` : Linux debian-t60 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

Digital Speech Decoder 1.7.0-dev (build:v1.6.0-86-g7ee04e5)
mbelib version 1.3.0

Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  7% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   PI Header    
Sync:  +DMR       mod: C4FM inlvl:  7%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  7% [slot0]  slot1   Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: C4FM inlvl:  7% [slot0]  slot1   VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7%  slot0  [slot1]  Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   PI Header    
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7%  slot0  [slot1]  Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  7%  slot0  [slot1]  Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: C4FM inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: C4FM inlvl:  7%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  MBC          
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  MBC          
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  7% [slot0]  slot1   Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  9% [slot0]  slot1   CSBK         
Sync:  +DMR       mod: GFSK inlvl:  9%  slot0  [slot1]  MBC          
Sync:  +DMR       mod: C4FM inlvl:  9% [slot0]  slot1   PI Header    
Sync:  +DMR       mod: C4FM inlvl:  8%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   MBC          
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   VOICE Header 
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   PI Header    
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   RATE 1/2 DATA
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   VOICE Header 
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  VOICE Header 
Sync:  +DMR       mod: C4FM inlvl:  8% [slot0]  slot1   Unknown burst type: 1101
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Slot idle    
Sync:  +DMR       mod: GFSK inlvl:  8%  slot0  [slot1]  PI Header    
Sync:  +DMR       mod: GFSK inlvl:  8% [slot0]  slot1   Unknown burst type: 1101

**Comment by szechyjs** [comment] 2018-05-07 15:49
Duplicate of #58

**Closed by szechyjs** 2018-05-07 15:49 UTC
